[package]
name = "ftth-rtnl"
version = "0.1.0"
edition = "2024"

[dependencies]
ftth-common = "0.1"
futures = "0.3.31"
ipnet = "2.11"
log = "0.4.28"
netlink-packet-core = "0.8"
netlink-packet-route = "0.25"
netlink-proto = "0.12"
rtnetlink = "0.18"
tokio = { version = "1", features = ["full"] }
